default_language_version:
    python: python3.10
repos:
-   repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    - id: black
      language_version: python3.10
# -   repo: https://gitlab.com/pycqa/flake8
#     rev: 3.9.2
#     hooks:
#     - id: flake8
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.1.0
    hooks:
    -   id: reorder-python-imports
        args: ['--application-directories=uniquehist:tests']
- repo: https://github.com/charliermarsh/ruff-pre-commit
  # Ruff version.
  rev: "v0.0.265"
  hooks:
    - id: ruff
- repo: https://github.com/kynan/nbstripout
  rev: 0.6.1
  hooks:
    - id: nbstripout
